### PR TITLE
Update to 21.08 runtimes

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by jurf** [comment]
Cheers, didn’t fully realise 21.08 was out. 😁

**Comment by akurtakov** [comment]
would you please push the build https://flathub.org/builds/#/builders/32/builds/65734 ?

**Comment by jurf** [comment]
Sure, but it happens automatically; there’s just a default wait (2 hours, I think) to be able to test it out.

**Comment by akurtakov** [comment]
Ah, thanks. I didn't knew that and always made sure I publish myself :)

**Pull request merged**
